#!/usr/bin/env ruby

class Deploy
  class << self
    def build
      command = "jekyll build"
      puts "Build Started"
      system(command)
      puts "Build Complete"
    end

    def git_tasks

    end

    def sync
      command = "rsync -av ./_site/* zeebee@iad1-shared-b8-05.dreamhost.com:/home/zeebee/zacbaston.com"
      puts "Deploying to Dreamhost"
      system(command)
    end

    def call
      begin
        build
        sync
      rescue Exception => e
        puts "Error: #{e}"
      end
    end
  end
end

Deploy.call